---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prober-v1

nameSuffix: -v1

commonLabels:
  version: v1

resources:
  - ../../apps/prober

patchesStrategicMerge:
  - prober.env.patch.yaml
