---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prober
spec:
  template:
    spec:
      containers:
      - name: prober
        env:
        - name: SERVICE_TO_CURL
          value: echo.echo.svc.cluster.local:63636
        - name: HEADER
          value: "x-version: v1"
