---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prober
spec:
  template:
    spec:
      containers:
      - name: prober
        env:
        # https://kubernetes.io/docs/concepts/workloads/pods/downward-api/
        - name: pod_name
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: pod_namespace
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: pod_ip
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: host_ip
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: node_name
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: service_account
          valueFrom:
            fieldRef:
              fieldPath: spec.serviceAccountName
        - name: version
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['version']
        - name: app
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['app']
        - name: SERVICE_TO_CURL
          value: echo.echo.svc.cluster.local:63636
