---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prober-v3

nameSuffix: -v3

commonLabels:
  version: v3

resources:
  - ../../apps/prober

patchesStrategicMerge:
  - prober.env.patch.yaml
