
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prober
spec:
  template:
    spec:
      containers:
        - name: prober
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 100Mi
