
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prober
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prober
  template:
    metadata:
      labels:
        app: prober
    spec:
      serviceAccountName: prober
      restartPolicy: Always
      containers:
        - name: prober
          image: fl64/prober:latest
          command: ["/entrypoint.sh"]
          volumeMounts:
            - name: prober-entrypoint
              mountPath: /entrypoint.sh
              subPath: entrypoint.sh
      volumes:
        - name: prober-entrypoint
          configMap:
            name: prober-entrypoint
            defaultMode: 0777
