---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prober

resources:
  - ./prober.yaml
  - ./ns.yaml

commonLabels:
  app: prober
  version: v1

configMapGenerator:
- name: prober-entrypoint
  files:
  - entrypoint.sh

patchesStrategicMerge:
  - prober.env.patch.yaml
