---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prober

nameSuffix: -v0

commonLabels:
  version: v0

resources:
  - ../../apps/prober

patchesStrategicMerge:
  - prober.env.patch.yaml
